In [8]:
import scipy.linalg as spl
import numpy as np

In [5]:
kek = np.asarray([[     1 ,   -1 ,   -1 ,   -1 ,   -1],
    [-1   ,  2     ,0  ,   0,     0],
    [-1  ,   0 ,    3  ,   1,     1],
    [-1 ,    0,     1 ,    4,     2],
    [-1,     0  ,   1,     2,     5]])

In [6]:
kek

array([[ 1, -1, -1, -1, -1],
       [-1,  2,  0,  0,  0],
       [-1,  0,  3,  1,  1],
       [-1,  0,  1,  4,  2],
       [-1,  0,  1,  2,  5]])

In [10]:
kekistan = spl.cholesky(kek)

In [11]:
kekistan

array([[ 1., -1., -1., -1., -1.],
       [ 0.,  1., -1., -1., -1.],
       [ 0.,  0.,  1., -1., -1.],
       [ 0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [12]:
kekboss = np.arange(5)+1

In [13]:
kekboss.shape = (5,1)

In [14]:
kekboss

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [17]:
spl.cho_solve(kekistan,kekboss)

ValueError: too many values to unpack (expected 2)

In [16]:
import csi

In [18]:
kekistan2 = spl.cho_factor(kek)

In [19]:
kekistan

array([[ 1., -1., -1., -1., -1.],
       [ 0.,  1., -1., -1., -1.],
       [ 0.,  0.,  1., -1., -1.],
       [ 0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [22]:
spl.cho_solve(kekistan2,kekboss)

array([[ 326.],
       [ 164.],
       [  84.],
       [  46.],
       [  31.]])

In [21]:
kekistan2

(array([[ 1., -1., -1., -1., -1.],
        [-1.,  1., -1., -1., -1.],
        [-1.,  0.,  1., -1., -1.],
        [-1.,  0.,  1.,  1., -1.],
        [-1.,  0.,  1.,  2.,  1.]]), False)

In [24]:
inp=csi.loadData('testdata/Botrytis_Data_normalised.csv')

In [32]:
inp2 = np.zeros((92,4))

In [33]:
inp2

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  

In [34]:
numtemp = np.arange(96)

In [35]:
inp2[:,:3] = inp.values[np.delete(numtemp,[23,47,71,95]),:3]

In [36]:
inp2

array([[ -1.00512755e+00,  -9.01463542e-01,   1.47698288e+00,
          0.00000000e+00],
       [  1.31742447e-01,   7.27479780e-01,   1.31862292e+00,
          0.00000000e+00],
       [  4.91480122e-01,   4.87647608e-01,  -9.25643771e-01,
          0.00000000e+00],
       [ -6.34662879e-01,   6.05024793e-01,   6.15759723e-01,
          0.00000000e+00],
       [ -5.53421891e-01,  -3.67126236e-01,  -2.96207532e-01,
          0.00000000e+00],
       [ -4.11932270e-02,   5.28851060e-01,   1.44064461e-01,
          0.00000000e+00],
       [ -4.59596153e-01,  -7.66496651e-01,  -4.79366778e-01,
          0.00000000e+00],
       [ -8.35011206e-01,   7.12055264e-01,   4.32066154e-01,
          0.00000000e+00],
       [ -8.14347064e-01,  -1.22044953e-01,  -4.06424465e-01,
          0.00000000e+00],
       [ -3.88057678e-01,  -6.00696999e-01,  -2.35287711e-01,
          0.00000000e+00],
       [ -1.48922359e+00,  -1.26008900e+00,  -7.93420717e-01,
          0.00000000e+00],
       [ -1.22886858e

In [37]:
inp.values[:,:3]

array([[ -1.00512755e+00,  -9.01463542e-01,   1.47698288e+00],
       [  1.31742447e-01,   7.27479780e-01,   1.31862292e+00],
       [  4.91480122e-01,   4.87647608e-01,  -9.25643771e-01],
       [ -6.34662879e-01,   6.05024793e-01,   6.15759723e-01],
       [ -5.53421891e-01,  -3.67126236e-01,  -2.96207532e-01],
       [ -4.11932270e-02,   5.28851060e-01,   1.44064461e-01],
       [ -4.59596153e-01,  -7.66496651e-01,  -4.79366778e-01],
       [ -8.35011206e-01,   7.12055264e-01,   4.32066154e-01],
       [ -8.14347064e-01,  -1.22044953e-01,  -4.06424465e-01],
       [ -3.88057678e-01,  -6.00696999e-01,  -2.35287711e-01],
       [ -1.48922359e+00,  -1.26008900e+00,  -7.93420717e-01],
       [ -1.22886858e+00,  -7.75928121e-01,  -5.07110266e-01],
       [  3.20981214e-01,  -5.76646285e-01,  -6.44974158e-01],
       [ -1.20544191e+00,  -1.64945400e-03,   2.96044545e-01],
       [ -7.74148311e-01,  -7.67772108e-01,  -2.97467158e-01],
       [ -1.14128159e+00,  -2.12903136e+00,  -8.9511071

In [38]:
numtemp.shape

(96,)

In [40]:
inp2[:,3] = inp.values[np.delete(numtemp,[0,24,48,72]),0]

In [41]:
inp2

array([[ -1.00512755e+00,  -9.01463542e-01,   1.47698288e+00,
          1.31742447e-01],
       [  1.31742447e-01,   7.27479780e-01,   1.31862292e+00,
          4.91480122e-01],
       [  4.91480122e-01,   4.87647608e-01,  -9.25643771e-01,
         -6.34662879e-01],
       [ -6.34662879e-01,   6.05024793e-01,   6.15759723e-01,
         -5.53421891e-01],
       [ -5.53421891e-01,  -3.67126236e-01,  -2.96207532e-01,
         -4.11932270e-02],
       [ -4.11932270e-02,   5.28851060e-01,   1.44064461e-01,
         -4.59596153e-01],
       [ -4.59596153e-01,  -7.66496651e-01,  -4.79366778e-01,
         -8.35011206e-01],
       [ -8.35011206e-01,   7.12055264e-01,   4.32066154e-01,
         -8.14347064e-01],
       [ -8.14347064e-01,  -1.22044953e-01,  -4.06424465e-01,
         -3.88057678e-01],
       [ -3.88057678e-01,  -6.00696999e-01,  -2.35287711e-01,
         -1.48922359e+00],
       [ -1.48922359e+00,  -1.26008900e+00,  -7.93420717e-01,
         -1.22886858e+00],
       [ -1.22886858e

In [42]:
np.savetxt('testdata/foo.csv',inp2,delimiter=',')

In [43]:
hypers = np.asarray([0.4270,-0.3249,-0.1958])

In [51]:
X = inp2[:,:3]

In [45]:
	thing = X / sp.exp(hypers[0])
	dist = np.zeros((len(Y),len(Y)))
	for i in np.arange(len(Y)):
		for j in np.arange(len(Y)):
			dist[i,j] = np.sum(np.square(thing[i,:]-thing[j,:]))
	K = sp.exp(2*hypers[1]+(-1/2)*dist)

NameError: name 'Y' is not defined

In [53]:
Y = inp2[:,3]

In [54]:
	thing = X / sp.exp(hypers[0])
	dist = np.zeros((len(Y),len(Y)))
	for i in np.arange(len(Y)):
		for j in np.arange(len(Y)):
			dist[i,j] = np.sum(np.square(thing[i,:]-thing[j,:]))
	K = sp.exp(2*hypers[1]+(-1/2)*dist)

In [55]:
K

array([[ 0.5221502 ,  0.22423824,  0.06291223, ...,  0.13165395,
         0.04664555,  0.25366334],
       [ 0.22423824,  0.5221502 ,  0.17175616, ...,  0.07482182,
         0.26895238,  0.37806283],
       [ 0.06291223,  0.17175616,  0.5221502 , ...,  0.19705782,
         0.2562501 ,  0.34245529],
       ..., 
       [ 0.13165395,  0.07482182,  0.19705782, ...,  0.5221502 ,
         0.03080422,  0.25225259],
       [ 0.04664555,  0.26895238,  0.2562501 , ...,  0.03080422,
         0.5221502 ,  0.2214744 ],
       [ 0.25366334,  0.37806283,  0.34245529, ...,  0.25225259,
         0.2214744 ,  0.5221502 ]])

In [49]:
inp2[:5,:]

array([[-1.00512755, -0.90146354,  1.47698288,  0.13174245],
       [ 0.13174245,  0.72747978,  1.31862292,  0.49148012],
       [ 0.49148012,  0.48764761, -0.92564377, -0.63466288],
       [-0.63466288,  0.60502479,  0.61575972, -0.55342189],
       [-0.55342189, -0.36712624, -0.29620753, -0.04119323]])

In [50]:
X[:5,:]

array([[-1.00512755, -0.90146354],
       [ 0.13174245,  0.72747978],
       [ 0.49148012,  0.48764761],
       [-0.63466288,  0.60502479],
       [-0.55342189, -0.36712624]])

In [56]:
K.shape

(92, 92)

In [57]:
def loglik(X,Y,hypers):
	#hypers as [length, signal std, noise std] in log space
	thing = X / sp.exp(hypers[0])
	dist = np.zeros((len(Y),len(Y)))
	for i in np.arange(len(Y)):
		for j in np.arange(len(Y)):
			dist[i,j] = np.sum(np.square(thing[i,:]-thing[j,:]))
	K = sp.exp(2*hypers[1]+(-1/2)*dist)
	L = spl.cho_factor(K + sp.exp(2*hypers[2])*npm.eye(len(Y)))
	#the alpha line is where shit hits the fan
	alpha = spl.cho_solve(np.transpose(L),spl.cho_solve(L,Y))
	out = (-0.5)*np.dot(np.transpose(Y),alpha)-np.sum(np.eye(len(Y))*np.log(L))-(X.shape[0]/2)*np.log(2*math.pi)
	return out

In [60]:
loglik(X,Y,hypers)

AttributeError: 'numpy.ndarray' object has no attribute 'log'

In [59]:
import numpy.matlib as npm

In [61]:
L = spl.cho_factor(K + sp.exp(2*hypers[2])*npm.eye(len(Y)))

In [62]:
alpha = spl.cho_solve(np.transpose(L),spl.cho_solve(L,Y))

In [75]:
out = (-0.5)*np.dot(np.transpose(Y),alpha)-np.sum(np.log(np.matrix((np.diag(L)))))-(X.shape[0]/2)*np.log(2*math.pi)

AttributeError: 'numpy.ndarray' object has no attribute 'log'

In [73]:
import math
from numpy import log as mylog

In [77]:
L

(array([[ 1.0945888 ,  0.20486071,  0.05747567, ...,  0.12027709,
          0.04261468,  0.23174304],
        [ 0.22423824,  1.07524729,  0.14878591, ...,  0.04666998,
          0.24201159,  0.30745279],
        [ 0.06291223,  0.17175616,  1.08290533, ...,  0.16917543,
          0.20111903,  0.26169514],
        ..., 
        [ 0.13165395,  0.07482182,  0.19705782, ...,  0.87775957,
          0.00322673, -0.00594007],
        [ 0.04664555,  0.26895238,  0.2562501 , ...,  0.03080422,
          0.86749054, -0.00466186],
        [ 0.25366334,  0.37806283,  0.34245529, ...,  0.25225259,
          0.2214744 ,  0.83709603]]), False)

In [78]:
np.transpose(L)

array([ array([[ 1.0945888 ,  0.20486071,  0.05747567, ...,  0.12027709,
         0.04261468,  0.23174304],
       [ 0.22423824,  1.07524729,  0.14878591, ...,  0.04666998,
         0.24201159,  0.30745279],
       [ 0.06291223,  0.17175616,  1.08290533, ...,  0.16917543,
         0.20111903,  0.26169514],
       ..., 
       [ 0.13165395,  0.07482182,  0.19705782, ...,  0.87775957,
         0.00322673, -0.00594007],
       [ 0.04664555,  0.26895238,  0.2562501 , ...,  0.03080422,
         0.86749054, -0.00466186],
       [ 0.25366334,  0.37806283,  0.34245529, ...,  0.25225259,
         0.2214744 ,  0.83709603]]),
       False], dtype=object)

In [79]:
	L = spl.cho_factor(K + sp.exp(2*hypers[2])*npm.eye(len(Y)))
	#the alpha line is where shit hits the fan
	alpha = spl.cho_solve((np.transpose(L[0]),L[1]),spl.cho_solve(L,Y))

In [80]:
L

(array([[ 1.0945888 ,  0.20486071,  0.05747567, ...,  0.12027709,
          0.04261468,  0.23174304],
        [ 0.22423824,  1.07524729,  0.14878591, ...,  0.04666998,
          0.24201159,  0.30745279],
        [ 0.06291223,  0.17175616,  1.08290533, ...,  0.16917543,
          0.20111903,  0.26169514],
        ..., 
        [ 0.13165395,  0.07482182,  0.19705782, ...,  0.87775957,
          0.00322673, -0.00594007],
        [ 0.04664555,  0.26895238,  0.2562501 , ...,  0.03080422,
          0.86749054, -0.00466186],
        [ 0.25366334,  0.37806283,  0.34245529, ...,  0.25225259,
          0.2214744 ,  0.83709603]]), False)

In [81]:
np.transpose(L[0])

array([[ 1.0945888 ,  0.22423824,  0.06291223, ...,  0.13165395,
         0.04664555,  0.25366334],
       [ 0.20486071,  1.07524729,  0.17175616, ...,  0.07482182,
         0.26895238,  0.37806283],
       [ 0.05747567,  0.14878591,  1.08290533, ...,  0.19705782,
         0.2562501 ,  0.34245529],
       ..., 
       [ 0.12027709,  0.04666998,  0.16917543, ...,  0.87775957,
         0.03080422,  0.25225259],
       [ 0.04261468,  0.24201159,  0.20111903, ...,  0.00322673,
         0.86749054,  0.2214744 ],
       [ 0.23174304,  0.30745279,  0.26169514, ..., -0.00594007,
        -0.00466186,  0.83709603]])

In [82]:
	out = (-0.5)*np.dot(np.transpose(Y),alpha)-np.sum(np.eye(len(Y))*np.log(L[0]))-(X.shape[0]/2)*np.log(2*math.pi)

In [83]:
out

nan

In [84]:
alpha

array([ 1.52176732,  0.87070757, -0.61571956, -1.13089812,  1.74340983,
       -0.95866364,  0.21671299, -1.87695455,  1.03237898, -1.69103484,
       -2.17523857,  3.17669233, -0.59232309, -0.78574546, -1.50299755,
       -0.46287273, -1.14708703, -0.9206235 ,  3.02596402, -0.60368039,
        1.31265034,  5.04962369, -1.36824377, -2.38048531, -3.6188641 ,
        2.59445587,  2.54598981,  1.4356734 , -2.97612551, -2.10173714,
        4.17667563, -1.73014942,  2.91585329, -3.09814898,  2.24630528,
       -0.59082381, -1.12255036, -1.65109991, -0.74568644, -0.08232334,
       -1.70271297,  0.94155791, -0.91807819, -0.91427347,  2.60566978,
        0.75497404, -0.11351264, -2.79398409,  0.94104973,  2.75574384,
       -1.11121407, -0.97924155,  0.89051751,  4.24247554, -2.30751827,
        0.2859884 ,  0.64178196, -0.47020849, -2.03952344,  0.0933288 ,
       -1.68867866, -1.20629418,  1.33755367,  0.08170153,  0.82799468,
       -0.68433245,  2.2687198 ,  0.14943726, -0.60799792, -2.59

In [85]:
	L = spl.cho_factor(K + sp.exp(2*hypers[2])*npm.eye(len(Y)))

In [87]:
L[0][:5,:5]

array([[ 1.0945888 ,  0.20486071,  0.05747567,  0.24405994,  0.22010731],
       [ 0.22423824,  1.07524729,  0.14878591,  0.33803513,  0.15353102],
       [ 0.06291223,  0.17175616,  1.08290533,  0.16194376,  0.26790696],
       [ 0.26714528,  0.41346965,  0.23969214,  0.99903246,  0.20842007],
       [ 0.240927  ,  0.21017515,  0.32561194,  0.35722253,  1.00543154]])

In [91]:
L2 = (np.triu(L[0]),L[1])

In [93]:
L2 = (np.transpose(L2[0]),True)

In [95]:
spl.cho_solve(L,Y)

array([ 0.60686042,  0.49208805, -0.59076297, -0.82709149,  0.43907554,
       -0.72577839, -0.67889293, -1.23159871, -0.21687727, -1.62104198,
       -1.68773366,  0.76573656, -1.11899712, -0.83350676, -1.17934302,
       -0.33676878, -0.6115338 , -0.22946871,  1.8770129 ,  0.28733735,
        1.44825314,  3.24837492, -0.89228346, -0.58066673, -0.7581299 ,
        1.9989341 ,  1.51080592,  0.79054136, -1.10998636,  0.1205456 ,
        1.88779521, -1.2909211 ,  1.9653673 , -1.79276462,  1.32598252,
       -0.53815923, -0.83537136, -1.00780137, -0.66910699, -0.58819913,
       -0.94594447,  0.25605226, -0.50532462,  0.12005507,  1.39331783,
        0.29902138,  0.69377141, -0.64004268,  0.8931187 ,  1.66536203,
        0.00846925,  0.0207665 ,  1.24562942,  2.3350203 , -0.74593292,
        1.09837206,  0.68584217, -0.24247337, -0.64428197, -0.0369654 ,
       -1.18345107, -0.63909111,  0.24212505, -0.3916145 , -0.74083602,
       -0.51039391,  0.32495967, -0.79241579, -1.05875748, -1.82

In [96]:
alpha = spl.cho_solve(L,Y)

In [97]:
alpha

array([ 0.60686042,  0.49208805, -0.59076297, -0.82709149,  0.43907554,
       -0.72577839, -0.67889293, -1.23159871, -0.21687727, -1.62104198,
       -1.68773366,  0.76573656, -1.11899712, -0.83350676, -1.17934302,
       -0.33676878, -0.6115338 , -0.22946871,  1.8770129 ,  0.28733735,
        1.44825314,  3.24837492, -0.89228346, -0.58066673, -0.7581299 ,
        1.9989341 ,  1.51080592,  0.79054136, -1.10998636,  0.1205456 ,
        1.88779521, -1.2909211 ,  1.9653673 , -1.79276462,  1.32598252,
       -0.53815923, -0.83537136, -1.00780137, -0.66910699, -0.58819913,
       -0.94594447,  0.25605226, -0.50532462,  0.12005507,  1.39331783,
        0.29902138,  0.69377141, -0.64004268,  0.8931187 ,  1.66536203,
        0.00846925,  0.0207665 ,  1.24562942,  2.3350203 , -0.74593292,
        1.09837206,  0.68584217, -0.24247337, -0.64428197, -0.0369654 ,
       -1.18345107, -0.63909111,  0.24212505, -0.3916145 , -0.74083602,
       -0.51039391,  0.32495967, -0.79241579, -1.05875748, -1.82

In [98]:
out = (-0.5)*np.dot(np.transpose(Y),alpha)-np.sum(np.eye(len(Y))*np.log(L[0]))-(X.shape[0]/2)*np.log(2*math.pi)

In [99]:
out

nan

In [100]:
(-0.5)*np.dot(np.transpose(Y),alpha)

-44.055576156704575

In [101]:
np.sum(np.eye(len(Y))*np.log(L[0]))

nan

In [106]:
np.diag(np.log(L[0]))

array([ 0.09037877,  0.07255067,  0.07964755, -0.00096801,  0.00541684,
       -0.06779548, -0.03062884, -0.06640526, -0.08367822, -0.09797674,
       -0.00053127, -0.09351584, -0.06637843, -0.09713265, -0.13064384,
       -0.00792269, -0.13818467, -0.08748028, -0.14192813, -0.03473246,
       -0.10280604, -0.05421409,  0.05764502, -0.09844239, -0.13369984,
       -0.15392588, -0.08525115, -0.09303881, -0.10776124, -0.1339301 ,
       -0.15119254, -0.09839613, -0.05700691, -0.09296761, -0.12976537,
       -0.13717299, -0.15541391, -0.13877431, -0.11812539, -0.16377859,
       -0.15154404, -0.07067481, -0.15264139, -0.1584932 , -0.1581323 ,
       -0.1337203 , -0.12948008, -0.15562449, -0.16126174, -0.12159995,
       -0.09028524, -0.1281282 , -0.13960235, -0.14848717, -0.12370696,
       -0.15056901, -0.16302623, -0.16578248, -0.17044064, -0.16739492,
       -0.16858049, -0.164848  , -0.13905376, -0.09762399, -0.16516505,
       -0.17495863, -0.17258724, -0.14976613, -0.15672323, -0.10

In [107]:
out = (-0.5)*np.dot(np.transpose(Y),alpha)-np.sum(np.diag(np.log(L[0])))-(X.shape[0]/2)*np.log(2*math.pi)

In [108]:
out

-117.91824959521513

In [109]:
def loglik(X,Y,hypers):
	#hypers as [length, signal std, noise std] in log space
	thing = X / sp.exp(hypers[0])
	dist = np.zeros((len(Y),len(Y)))
	for i in np.arange(len(Y)):
		for j in np.arange(len(Y)):
			dist[i,j] = np.sum(np.square(thing[i,:]-thing[j,:]))
	K = sp.exp(2*hypers[1]+(-1/2)*dist)
	L = spl.cho_factor(K + sp.exp(2*hypers[2])*npm.eye(len(Y)))
	#the alpha line is where shit hits the fan
	#alpha = spl.cho_solve((np.transpose(L[0]),L[1]),spl.cho_solve(L,Y))
	#for some crazy reason this gives the same results as matlab instead
	alpha = spl.cho_solve(L,Y)
	#out = (-0.5)*np.dot(np.transpose(Y),alpha)-np.sum(np.eye(len(Y))*np.log(L[0]))-(X.shape[0]/2)*np.log(2*math.pi)
	out = (-0.5)*np.dot(np.transpose(Y),alpha)-np.sum(np.diag(np.log(L[0])))-(X.shape[0]/2)*np.log(2*math.pi)
	return out

In [110]:
loglik(X,Y,hypers)

-117.91824959521513

In [111]:
X2 = X[:,:2]

In [117]:
loglik(X2,Y,hypers)

-117.61962801619026

In [113]:
alpha

array([ 0.60686042,  0.49208805, -0.59076297, -0.82709149,  0.43907554,
       -0.72577839, -0.67889293, -1.23159871, -0.21687727, -1.62104198,
       -1.68773366,  0.76573656, -1.11899712, -0.83350676, -1.17934302,
       -0.33676878, -0.6115338 , -0.22946871,  1.8770129 ,  0.28733735,
        1.44825314,  3.24837492, -0.89228346, -0.58066673, -0.7581299 ,
        1.9989341 ,  1.51080592,  0.79054136, -1.10998636,  0.1205456 ,
        1.88779521, -1.2909211 ,  1.9653673 , -1.79276462,  1.32598252,
       -0.53815923, -0.83537136, -1.00780137, -0.66910699, -0.58819913,
       -0.94594447,  0.25605226, -0.50532462,  0.12005507,  1.39331783,
        0.29902138,  0.69377141, -0.64004268,  0.8931187 ,  1.66536203,
        0.00846925,  0.0207665 ,  1.24562942,  2.3350203 , -0.74593292,
        1.09837206,  0.68584217, -0.24247337, -0.64428197, -0.0369654 ,
       -1.18345107, -0.63909111,  0.24212505, -0.3916145 , -0.74083602,
       -0.51039391,  0.32495967, -0.79241579, -1.05875748, -1.82

In [114]:
L[0][:5,:5]

array([[ 1.0945888 ,  0.20486071,  0.05747567,  0.24405994,  0.22010731],
       [ 0.22423824,  1.07524729,  0.14878591,  0.33803513,  0.15353102],
       [ 0.06291223,  0.17175616,  1.08290533,  0.16194376,  0.26790696],
       [ 0.26714528,  0.41346965,  0.23969214,  0.99903246,  0.20842007],
       [ 0.240927  ,  0.21017515,  0.32561194,  0.35722253,  1.00543154]])

In [115]:
np.sum(np.log(np.diag(L[0])))

-10.679671616319323

In [116]:
(X.shape[0]/2)*np.log(2*math.pi)

84.54234505482988

In [118]:
inp

sample,replicate Botrytis:A                                                    \
hours                    2         4         6         8         10        12   
AT4G34000         -1.005128 -0.901464  1.476983  0.789920  2.220758 -0.742055   
AT3G19290          0.131742  0.727480  1.318623  0.008204  0.542562  0.486430   
AT2G40220          0.491480  0.487648 -0.925644 -0.452926 -0.567622 -0.366723   
AT2G36270         -0.634663  0.605025  0.615760  0.556027  0.410010 -0.197133   
AT1G01480         -0.553422 -0.367126 -0.296208 -0.452172 -0.643295 -0.225244   
AT2G37620         -0.041193  0.528851  0.144064  0.254001  0.169677 -0.180386   
AT3G01420         -0.459596 -0.766497 -0.479367 -0.196882 -0.668417 -0.662900   
AT1G52890         -0.835011  0.712055  0.432066 -0.744258 -0.066746 -1.460871   
AT1G61110         -0.814347 -0.122045 -0.406424 -0.323429 -0.519370 -0.811562   
AT3G56530         -0.388058 -0.600697 -0.235288 -0.697230 -0.388342 -0.761105   
AT5G13180         -1.489224 -1.260089 -0.793421 -0.992342 -0.290238 -0.487424   
AT5G39610         -1.228869 -0.775928 -0.507110 -1.737271 -1.098974 -1.242380   
AT5G63790          0.320981 -0.576646 -0.644974 -4.095750 -0.359310 -0.880583   
AT5G62000         -1.205442 -0.001649  0.296045 -0.103269  0.161954  0.583389   
AT3G51910         -0.774148 -0.767772 -0.297467 -0.502312  0.052595 -1.570551   
AT1G06160         -1.141282 -2.129031 -0.895111 -1.182959 -1.728691 -0.088789   
AT1G25550         -0.392078 -0.453786 -0.537207 -0.691298 -0.493177  0.841963   
AT1G35560         -0.769818  0.069548  1.183649  0.417482  0.060061 -0.182406   
AT1G79320         -0.351360 -0.384523 -0.000062  0.072383 -0.017556 -0.147387   
AT2G18300          0.910799 -0.633085 -0.025166  0.630509 -0.774365  1.624884   
AT2G24430         -0.204610 -1.283726 -0.656418  0.701527 -0.331687  0.054834   
AT2G28510          0.612691  0.580645  1.037084  0.622505  0.636406 -1.277757   
AT2G40340          2.390346  0.907543  0.849250 -0.213001 -0.022548 -0.269348   
AT2G45220         -0.743120 -0.588827 -0.988962 -1.013902 -1.187917 -0.707875   
AT2G45800          0.454636  0.112405  0.945810 -0.756190  0.612675  0.560706   
AT3G13040         -0.385321  0.144645  0.911057 -0.862727  0.997087 -0.102305   
AT3G23220         -0.635886 -0.652295 -0.410527 -0.762081 -1.239927 -0.849516   
AT3G28320          1.002584  0.399360 -0.013068 -0.494704  0.616059  0.077852   
AT3G57600          0.972498  0.750495  1.018533  0.510972  0.289927  0.304370   
AT3G58120          0.760370  0.005720 -0.582616 -0.112553 -0.362966  3.058982   
...                     ...       ...       ...       ...       ...       ...   
AT3G06490          0.107170 -0.271704  0.262413 -0.023418 -0.266887  0.172300   
AT1G48000         -0.779418 -0.594572 -0.336327 -0.845115 -0.841455 -1.217656   
AT2G47190         -0.671534 -0.195952 -0.282939 -0.785406 -0.526383 -0.829013   
AT3G14440         -0.069890 -1.098826 -0.292534 -0.509413 -0.235187 -0.470453   
AT1G75390         -0.968599  0.130646 -0.186092  0.172221 -0.511223 -1.149849   
AT3G19580         -0.890373 -0.328737 -0.370660 -0.887172 -0.228427 -0.618847   
AT1G50420          1.006898  1.255948  1.375246  1.022556  0.101519 -1.007851   
AT3G02150         -1.001738  0.172501 -0.329857 -1.090665  0.299877  0.000086   
AT3G15500         -1.011552 -0.538055 -0.515022 -0.731683 -1.048983 -0.789392   
AT3G17790         -1.488075 -0.908746 -0.460022  0.058525 -0.058905 -2.342916   
AT3G48590         -0.184238  0.609002  1.229150 -0.439096  0.148396  0.931680   
AT4G24540         -0.861161  0.235213  0.709366  1.062896  0.230929  0.857280   
AT5G53980         -0.224618  0.288174  0.075009  0.346899 -0.441845 -0.395418   
AT2G38470         -0.526418 -0.013033  0.767008  0.255348  0.861070  0.108555   
AT4G13250          0.330296  0.780008  0.564865  0.077091 -0.165708 -0.713121   
AT5G06960          1.024128  0.526400  0.351080 -0.677345  0.556065 -0.089986   
AT5G61270          1.894113  1.

In [119]:
inp.iloc[:3,:]

sample,replicate Botrytis:A                                                    \
hours                    2         4         6         8         10        12   
AT4G34000         -1.005128 -0.901464  1.476983  0.789920  2.220758 -0.742055   
AT3G19290          0.131742  0.727480  1.318623  0.008204  0.542562  0.486430   
AT2G40220          0.491480  0.487648 -0.925644 -0.452926 -0.567622 -0.366723   

sample,replicate                                            ...       Mock:D  \
hours                   14        16        18        20    ...           30   
AT4G34000        -0.698624  1.105240  0.132847  1.366016    ...    -0.511834   
AT3G19290         0.632142 -0.009641  0.129336  0.220571    ...    -0.565398   
AT2G40220        -0.601311  1.216349 -0.150605 -0.885360    ...     0.487652   

sample,replicate                                                              \
hours                   32        34        36        38        40        42   
AT4G34000        -0.342761 -0.659265 -0.834555 -0.032315 -0.988220 -0.734723   
AT3G19290        -1.676135 -0.564693  0.144479 -0.061978 -0.999283 -1.954294   
AT2G40220         0.485202 -0.273837  0.684008  1.137494 -0.292608 -0.504142   

sample,replicate                                
hours                   44        46        48  
AT4G34000        -0.183527 -0.872434 -1.263834  
AT3G19290        -0.138208 -0.106360 -2.221531  
AT2G40220         0.346184 -0.163320 -1.063001  

[3 rows x 192 columns]

In [120]:
X

array([[ -1.00512755e+00,  -9.01463542e-01,   1.47698288e+00],
       [  1.31742447e-01,   7.27479780e-01,   1.31862292e+00],
       [  4.91480122e-01,   4.87647608e-01,  -9.25643771e-01],
       [ -6.34662879e-01,   6.05024793e-01,   6.15759723e-01],
       [ -5.53421891e-01,  -3.67126236e-01,  -2.96207532e-01],
       [ -4.11932270e-02,   5.28851060e-01,   1.44064461e-01],
       [ -4.59596153e-01,  -7.66496651e-01,  -4.79366778e-01],
       [ -8.35011206e-01,   7.12055264e-01,   4.32066154e-01],
       [ -8.14347064e-01,  -1.22044953e-01,  -4.06424465e-01],
       [ -3.88057678e-01,  -6.00696999e-01,  -2.35287711e-01],
       [ -1.48922359e+00,  -1.26008900e+00,  -7.93420717e-01],
       [ -1.22886858e+00,  -7.75928121e-01,  -5.07110266e-01],
       [  3.20981214e-01,  -5.76646285e-01,  -6.44974158e-01],
       [ -1.20544191e+00,  -1.64945400e-03,   2.96044545e-01],
       [ -7.74148311e-01,  -7.67772108e-01,  -2.97467158e-01],
       [ -1.14128159e+00,  -2.12903136e+00,  -8.9511071

In [121]:
cc = csi.Csi(inp.iloc[:3,:])

In [123]:
em = cc.getEm()

In [124]:
em.pset

[]

In [132]:
em.setup((['AT3G19290','AT2G40220'],'AT4G34000'))

ValueError: too many values to unpack (expected 2)

In [134]:
em.setup([cc.allParents('AT4G34000',2)[3]])

In [135]:
em.pset

[(['AT3G19290', 'AT2G40220'], 'AT4G34000')]

In [136]:
X

array([[ -1.00512755e+00,  -9.01463542e-01,   1.47698288e+00],
       [  1.31742447e-01,   7.27479780e-01,   1.31862292e+00],
       [  4.91480122e-01,   4.87647608e-01,  -9.25643771e-01],
       [ -6.34662879e-01,   6.05024793e-01,   6.15759723e-01],
       [ -5.53421891e-01,  -3.67126236e-01,  -2.96207532e-01],
       [ -4.11932270e-02,   5.28851060e-01,   1.44064461e-01],
       [ -4.59596153e-01,  -7.66496651e-01,  -4.79366778e-01],
       [ -8.35011206e-01,   7.12055264e-01,   4.32066154e-01],
       [ -8.14347064e-01,  -1.22044953e-01,  -4.06424465e-01],
       [ -3.88057678e-01,  -6.00696999e-01,  -2.35287711e-01],
       [ -1.48922359e+00,  -1.26008900e+00,  -7.93420717e-01],
       [ -1.22886858e+00,  -7.75928121e-01,  -5.07110266e-01],
       [  3.20981214e-01,  -5.76646285e-01,  -6.44974158e-01],
       [ -1.20544191e+00,  -1.64945400e-03,   2.96044545e-01],
       [ -7.74148311e-01,  -7.67772108e-01,  -2.97467158e-01],
       [ -1.14128159e+00,  -2.12903136e+00,  -8.9511071

In [137]:
em.X = X

In [138]:
em.Y = Y

In [139]:
hypers

array([ 0.427 , -0.3249, -0.1958])

In [141]:
hypers2 = hypers[[1,0,2]]

In [142]:
hypers2

array([-0.3249,  0.427 , -0.1958])

In [143]:
em.hypers = sp.exp(hypers2)

In [144]:
em.logliks()

array([-254.808269])

In [146]:
em = cc.getEm()

In [147]:
em.setup(cc.allParents('AT4G34000',2))

In [148]:
em.X

AT4G34000  AT3G19290  AT2G40220
sample,replicate hours                                 
Botrytis:A       2      -1.005128   0.131742   0.491480
                 4      -0.901464   0.727480   0.487648
                 6       1.476983   1.318623  -0.925644
                 8       0.789920   0.008204  -0.452926
                 10      2.220758   0.542562  -0.567622
                 12     -0.742055   0.486430  -0.366723
                 14     -0.698624   0.632142  -0.601311
                 16      1.105240  -0.009641   1.216349
                 18      0.132847   0.129336  -0.150605
                 20      1.366016   0.220571  -0.885360
                 22      0.292972   2.635230  -0.494566
                 24      0.485219   0.404590   2.465125
                 26      0.006670   0.446896   0.892726
                 28     -0.829932  -0.703055   1.529133
                 30      1.738602   0.638971  -0.114106
                 32      1.313264  -0.097418  -0.351060
                 34      0.083945  -0.280589  -0.804481
                 36     -0.477393   0.090701  -0.554374
                 38      2.177634   2.003104   0.061641
                 40      0.242574   0.654963  -0.626832
                 42      1.133351   0.570847  -0.485343
                 44      1.228888   0.187431  -1.132619
                 46      1.393030   0.549945  -1.580732
Botrytis:B       2      -1.003921   0.066419   1.030061
                 4      -0.267215   0.605971  -1.057123
                 6       0.165645   0.264831  -0.509710
                 8      -0.095233  -1.370873  -0.839040
                 10      0.148252  -0.331936   0.366360
                 12      0.035439   1.041481  -1.744034
                 14     -1.114506   0.050344  -0.873093
...                           ...        ...        ...
Mock:C           34     -0.583629  -0.705241   0.951077
                 36     -0.837824   0.203008  -1.391861
                 38     -0.854144  -1.053210   0.704545
                 40     -0.685294  -1.142034   0.040825
                 42     -1.316891  -0.152391   1.645528
                 44     -0.544141  -1.637163   0.491135
                 46     -1.306591  -0.737239   0.407031
Mock:D           2      -1.136219   1.040786   1.075453
                 4      -0.715827  -0.039095   0.557255
                 6       1.682788   1.858123   0.220498
                 8       1.403598   0.521354   0.619227
                 10      0.097377  -0.159891  -0.657865
                 12     -0.091661   0.236883   0.863272
                 14     -0.322104   0.514984  -1.112172
                 16      0.467650   0.919307  -0.163467
                 18      0.564302   0.801348  -0.329377
                 20      0.279039  -0.893018  -0.368949
                 22      0.425142   1.642539  -1.156958
                 24     -1.304963   1.196165   0.260375
                 26     -1.599202  -0.201134   0.637331
                 28     -0.673824  -1.389916   2.238813
                 30     -0.511834  -0.565398   0.487652
                 32     -0.342761  -1.676135   0.485202
                 34     -0.659265  -0.564693  -0.273837
                 36     -0.834555   0.144479   0.684008
                 38     -0.032315  -0.061978   1.137494
                 40     -0.988220  -0.999283  -0.292608
                 42     -0.734723  -1.954294  -0.504142
                 44     -0.183527  -0.138208   0.346184
                 46     -0.872434  -0.106360  -0.163320

[184 rows x 3 columns]

In [149]:
em.hypers = sp.exp(hypers2)

In [150]:
em.pset

[([], 'AT4G34000'),
 (['AT3G19290'], 'AT4G34000'),
 (['AT2G40220'], 'AT4G34000'),
 (['AT3G19290', 'AT2G40220'], 'AT4G34000')]

In [151]:
em.logliks()

array([-254.6006751 , -256.71541565, -252.65845607, -254.808269  ])

In [152]:
em.Y

AT4G34000  AT3G19290  AT2G40220
sample,replicate hours                                 
Botrytis:A       4      -0.901464   0.727480   0.487648
                 6       1.476983   1.318623  -0.925644
                 8       0.789920   0.008204  -0.452926
                 10      2.220758   0.542562  -0.567622
                 12     -0.742055   0.486430  -0.366723
                 14     -0.698624   0.632142  -0.601311
                 16      1.105240  -0.009641   1.216349
                 18      0.132847   0.129336  -0.150605
                 20      1.366016   0.220571  -0.885360
                 22      0.292972   2.635230  -0.494566
                 24      0.485219   0.404590   2.465125
                 26      0.006670   0.446896   0.892726
                 28     -0.829932  -0.703055   1.529133
                 30      1.738602   0.638971  -0.114106
                 32      1.313264  -0.097418  -0.351060
                 34      0.083945  -0.280589  -0.804481
                 36     -0.477393   0.090701  -0.554374
                 38      2.177634   2.003104   0.061641
                 40      0.242574   0.654963  -0.626832
                 42      1.133351   0.570847  -0.485343
                 44      1.228888   0.187431  -1.132619
                 46      1.393030   0.549945  -1.580732
                 48      0.465554  -0.023142   0.076523
Botrytis:B       4      -0.267215   0.605971  -1.057123
                 6       0.165645   0.264831  -0.509710
                 8      -0.095233  -1.370873  -0.839040
                 10      0.148252  -0.331936   0.366360
                 12      0.035439   1.041481  -1.744034
                 14     -1.114506   0.050344  -0.873093
                 16     -0.585816  -0.383840  -0.255229
...                           ...        ...        ...
Mock:C           36     -0.837824   0.203008  -1.391861
                 38     -0.854144  -1.053210   0.704545
                 40     -0.685294  -1.142034   0.040825
                 42     -1.316891  -0.152391   1.645528
                 44     -0.544141  -1.637163   0.491135
                 46     -1.306591  -0.737239   0.407031
                 48     -0.551625  -0.417232   0.336661
Mock:D           4      -0.715827  -0.039095   0.557255
                 6       1.682788   1.858123   0.220498
                 8       1.403598   0.521354   0.619227
                 10      0.097377  -0.159891  -0.657865
                 12     -0.091661   0.236883   0.863272
                 14     -0.322104   0.514984  -1.112172
                 16      0.467650   0.919307  -0.163467
                 18      0.564302   0.801348  -0.329377
                 20      0.279039  -0.893018  -0.368949
                 22      0.425142   1.642539  -1.156958
                 24     -1.304963   1.196165   0.260375
                 26     -1.599202  -0.201134   0.637331
                 28     -0.673824  -1.389916   2.238813
                 30     -0.511834  -0.565398   0.487652
                 32     -0.342761  -1.676135   0.485202
                 34     -0.659265  -0.564693  -0.273837
                 36     -0.834555   0.144479   0.684008
                 38     -0.032315  -0.061978   1.137494
                 40     -0.988220  -0.999283  -0.292608
                 42     -0.734723  -1.954294  -0.504142
                 44     -0.183527  -0.138208   0.346184
                 46     -0.872434  -0.106360  -0.163320
                 48     -1.263834  -2.221531  -1.063001

[184 rows x 3 columns]

In [154]:
loglik(em.X.values,em.Y.iloc[:,0].values,hypers)

-254.8082692620205

In [155]:
X

array([[ -1.00512755e+00,  -9.01463542e-01,   1.47698288e+00],
       [  1.31742447e-01,   7.27479780e-01,   1.31862292e+00],
       [  4.91480122e-01,   4.87647608e-01,  -9.25643771e-01],
       [ -6.34662879e-01,   6.05024793e-01,   6.15759723e-01],
       [ -5.53421891e-01,  -3.67126236e-01,  -2.96207532e-01],
       [ -4.11932270e-02,   5.28851060e-01,   1.44064461e-01],
       [ -4.59596153e-01,  -7.66496651e-01,  -4.79366778e-01],
       [ -8.35011206e-01,   7.12055264e-01,   4.32066154e-01],
       [ -8.14347064e-01,  -1.22044953e-01,  -4.06424465e-01],
       [ -3.88057678e-01,  -6.00696999e-01,  -2.35287711e-01],
       [ -1.48922359e+00,  -1.26008900e+00,  -7.93420717e-01],
       [ -1.22886858e+00,  -7.75928121e-01,  -5.07110266e-01],
       [  3.20981214e-01,  -5.76646285e-01,  -6.44974158e-01],
       [ -1.20544191e+00,  -1.64945400e-03,   2.96044545e-01],
       [ -7.74148311e-01,  -7.67772108e-01,  -2.97467158e-01],
       [ -1.14128159e+00,  -2.12903136e+00,  -8.9511071

In [156]:
em.X = X

In [157]:
em.Y = Y

In [164]:
em.hypers = sp.exp(hypers2)

In [168]:
em.logliks()

array([-254.6006751 , -256.71541565, -252.65845607, -254.808269  ])

In [161]:
X.shape

(92, 3)

In [169]:
em._updatell

False

In [170]:
em.X

array([[ -1.00512755e+00,  -9.01463542e-01,   1.47698288e+00],
       [  1.31742447e-01,   7.27479780e-01,   1.31862292e+00],
       [  4.91480122e-01,   4.87647608e-01,  -9.25643771e-01],
       [ -6.34662879e-01,   6.05024793e-01,   6.15759723e-01],
       [ -5.53421891e-01,  -3.67126236e-01,  -2.96207532e-01],
       [ -4.11932270e-02,   5.28851060e-01,   1.44064461e-01],
       [ -4.59596153e-01,  -7.66496651e-01,  -4.79366778e-01],
       [ -8.35011206e-01,   7.12055264e-01,   4.32066154e-01],
       [ -8.14347064e-01,  -1.22044953e-01,  -4.06424465e-01],
       [ -3.88057678e-01,  -6.00696999e-01,  -2.35287711e-01],
       [ -1.48922359e+00,  -1.26008900e+00,  -7.93420717e-01],
       [ -1.22886858e+00,  -7.75928121e-01,  -5.07110266e-01],
       [  3.20981214e-01,  -5.76646285e-01,  -6.44974158e-01],
       [ -1.20544191e+00,  -1.64945400e-03,   2.96044545e-01],
       [ -7.74148311e-01,  -7.67772108e-01,  -2.97467158e-01],
       [ -1.14128159e+00,  -2.12903136e+00,  -8.9511071

In [172]:
em.worker = csi.CsiEmWorker(em.X,em.Y,em.pset)

In [173]:
em._updatell=True

In [174]:
em.logliks()

AttributeError: 'numpy.ndarray' object has no attribute 'loc'

In [175]:
import gp

In [177]:
wot = gp.rbf(X,Y,sp.exp(hypers2))

In [178]:
wot.log_marginal()

IndexError: tuple index out of range

In [181]:
inp = csi.loadData('testdata/minibot.csv')

In [182]:
inp

sample,replicate Botrytis:A                                                    \
hours                    2         4         6         8         10        12   
AT4G34000         -1.005128 -0.901464  1.476983  0.789920  2.220758 -0.742055   
AT3G19290          0.131742  0.727480  1.318623  0.008204  0.542562  0.486430   
AT2G40220          0.491480  0.487648 -0.925644 -0.452926 -0.567622 -0.366723   

sample,replicate                                            ...    Botrytis:D  \
hours                   14        16        18        20    ...            30   
AT4G34000        -0.698624  1.105240  0.132847  1.366016    ...     -0.029930   
AT3G19290         0.632142 -0.009641  0.129336  0.220571    ...     -0.214592   
AT2G40220        -0.601311  1.216349 -0.150605 -0.885360    ...     -0.888115   

sample,replicate                                                              \
hours                   32        34        36        38        40        42   
AT4G34000         0.962882  1.055843 -0.843388 -1.025875  0.507842  1.231199   
AT3G19290         0.820397  1.561663  0.690160 -0.341749  0.481231  0.743498   
AT2G40220        -0.440157 -1.368726 -2.562297 -1.045923 -1.436556 -0.835877   

sample,replicate                                
hours                   44        46        48  
AT4G34000         0.393390  0.455947  1.245183  
AT3G19290        -1.061936  0.149846  1.389533  
AT2G40220        -0.851497 -0.634876  0.384761  

[3 rows x 96 columns]

In [183]:
cc = csi.Csi(inp)

In [184]:
em = cc.getEm()

In [185]:
em.setup(cc.allParents('AT4G34000',2))

In [186]:
em.hypers = sp.exp(hypers2)

In [187]:
em.logliks()

array([-121.3155958 , -121.5644043 , -121.34756558, -122.05483638])

In [188]:
em.X

AT4G34000  AT3G19290  AT2G40220
sample,replicate hours                                 
Botrytis:A       2      -1.005128   0.131742   0.491480
                 4      -0.901464   0.727480   0.487648
                 6       1.476983   1.318623  -0.925644
                 8       0.789920   0.008204  -0.452926
                 10      2.220758   0.542562  -0.567622
                 12     -0.742055   0.486430  -0.366723
                 14     -0.698624   0.632142  -0.601311
                 16      1.105240  -0.009641   1.216349
                 18      0.132847   0.129336  -0.150605
                 20      1.366016   0.220571  -0.885360
                 22      0.292972   2.635230  -0.494566
                 24      0.485219   0.404590   2.465125
                 26      0.006670   0.446896   0.892726
                 28     -0.829932  -0.703055   1.529133
                 30      1.738602   0.638971  -0.114106
                 32      1.313264  -0.097418  -0.351060
                 34      0.083945  -0.280589  -0.804481
                 36     -0.477393   0.090701  -0.554374
                 38      2.177634   2.003104   0.061641
                 40      0.242574   0.654963  -0.626832
                 42      1.133351   0.570847  -0.485343
                 44      1.228888   0.187431  -1.132619
                 46      1.393030   0.549945  -1.580732
Botrytis:B       2      -1.003921   0.066419   1.030061
                 4      -0.267215   0.605971  -1.057123
                 6       0.165645   0.264831  -0.509710
                 8      -0.095233  -1.370873  -0.839040
                 10      0.148252  -0.331936   0.366360
                 12      0.035439   1.041481  -1.744034
                 14     -1.114506   0.050344  -0.873093
...                           ...        ...        ...
Botrytis:C       34     -0.981274   0.021728  -0.960378
                 36     -0.638894  -0.309151  -1.371123
                 38     -0.148355   0.512964  -1.032651
                 40     -0.359394  -0.701293   0.052135
                 42      1.402870   0.514272  -0.407918
                 44      2.051209  -0.327811   0.558803
                 46      1.297884  -0.667845  -2.052714
Botrytis:D       2      -0.211502   0.260559   0.456169
                 4       0.162456  -0.000145   1.549790
                 6      -0.245225  -0.355137   0.076232
                 8      -0.220179   0.282561  -1.195644
                 10      1.269458   1.014213  -0.026294
                 12     -1.129423  -0.240227  -0.983892
                 14      0.015561   1.487986   0.503057
                 16     -0.034131   0.757225  -0.495548
                 18      1.277857   0.767032  -0.871869
                 20      0.527890   0.124702  -1.273525
                 22      0.544121   1.945272   1.273410
                 24      0.089157   0.937585  -0.236770
                 26      1.329090   1.360379   1.078242
                 28      0.559652   0.690992   0.887027
                 30     -0.029930  -0.214592  -0.888115
                 32      0.962882   0.820397  -0.440157
                 34      1.055843   1.561663  -1.368726
                 36     -0.843388   0.690160  -2.562297
                 38     -1.025875  -0.341749  -1.045923
                 40      0.507842   0.481231  -1.436556
                 42      1.231199   0.743498  -0.835877
                 44      0.393390  -1.061936  -0.851497
                 46      0.455947   0.149846  -0.634876

[92 rows x 3 columns]

In [189]:
X = em.X.values

In [190]:
loglik(em.X.values,em.Y.values[:,0],hypers)

-122.05483641766256

In [191]:
cc = csi.loadData('testdata/dreamA.csv')

In [193]:
inp = cc

In [194]:
cc = csi.Csi(inp)

In [195]:
em = cc.getEm()

In [196]:
em.setup(cc.allParents('G1',2))

In [197]:
em.hypers = np.asarray([0.98620514,1.04708901,0.41466598])

In [198]:
hypers = sp.log(np.asarray([1.04708901,0.98629514,0.41466598]))

In [199]:
em.logliks()

array([-23.27894137, -18.32594796, -18.7444161 , -24.42604534,
       -22.13206265, -25.92167698, -23.81324764, -25.05379811,
       -25.29477767, -23.10655357, -19.58811131, -19.90227648,
       -18.22637719, -20.60300281, -19.3650163 , -20.21075753,
       -21.82035871, -18.58256788, -20.26175185, -18.19795132,
       -21.05097855, -19.6186531 , -20.72639174, -21.70468242,
       -18.38865654, -24.01432027, -27.03401191, -25.1694436 ,
       -26.24346656, -26.81696488, -24.90621435, -24.90054689,
       -23.15761612, -24.31850849, -25.10749537, -23.34589862,
       -26.18265748, -26.92490081, -27.46070102, -25.21803195,
       -25.67022598, -25.66015668, -24.05926358, -27.14938294,
       -24.48412499, -25.47884979])

In [200]:
X=np.transpose(inp.values[:2,:-1])

In [201]:
Y=np.transpose(inp.values[0,1:])

In [202]:
Y.shape

(20,)

In [203]:
Y

array([-0.83196402, -1.43941838, -1.73750543, -1.74993984, -1.75652574,
       -1.76581167, -1.76905961, -1.76069355, -1.75907493, -1.7468111 ,
       -1.06556209, -0.64965932, -0.62917288, -0.25720773, -0.38067219,
        0.46331497,  1.03723934,  1.08388152,  1.28839774,  1.41151283])

In [204]:
Y.shape = (20,1)

In [205]:
Y

array([[-0.83196402],
       [-1.43941838],
       [-1.73750543],
       [-1.74993984],
       [-1.75652574],
       [-1.76581167],
       [-1.76905961],
       [-1.76069355],
       [-1.75907493],
       [-1.7468111 ],
       [-1.06556209],
       [-0.64965932],
       [-0.62917288],
       [-0.25720773],
       [-0.38067219],
       [ 0.46331497],
       [ 1.03723934],
       [ 1.08388152],
       [ 1.28839774],
       [ 1.41151283]])

In [206]:
X.shape

(20, 2)

In [207]:
loglik(X,Y,hypers)

array([[-18.32576614]])