In [1]:
import numpy as np
import scipy as sp
import csi
from hcsi import *

In [2]:
inp = csi.loadData('testdata/dream4-csidata_normalised.csv')

In [3]:
gpprior = [10,0.1]
betaprior = [1,1]

In [4]:
genes = inp.index

In [5]:
gene = 'G1'

In [20]:
	hnrv = RandomVariableHyperNetwork(inp,gene,2)
	crv = []
	conditions = np.unique([x[0] for x in inp.columns.values])
	for cond in conditions:
		crv.append(RandomVariableCondition(inp,cond,gene,gpprior,betaprior,2,True))
	gibbs = GibbsHCSI(crv,hnrv)

In [21]:
gibbs.rvl[0].em.hypers

array([ 0.41865948,  3.78699698,  1.7099005 ])

In [35]:
for i in np.arange(len(conditions)):
    gibbs.rvl[i].em.hypers = np.asarray([1,1,1])

In [23]:
gibbs.rvl[0].em.hypers

array([[ 1.,  1.,  1.]])

In [24]:
gibbs.rvl[0].em.X

G1        G2        G3        G4        G5        G6  \
condition time                                                               
A         0     1.457348 -0.947806  1.900531 -0.587374 -1.141544 -0.969230   
          50   -0.181595  1.801261  1.297516 -0.642793  0.828327 -1.091449   
          100  -0.684896  1.333486  0.580768 -0.580669  0.540489 -0.586762   
          150  -0.931874 -0.665083  0.809447 -0.567492  1.209848 -0.077659   
          200  -0.942176  0.015306  0.143316 -0.538813  0.936783  0.501003   
          250  -0.947633  0.586631 -0.215506  0.197373  0.802652  0.809808   
          300  -0.955327  0.158302 -0.483748 -0.359098  0.821430  1.044403   
          350  -0.958018  0.279842 -0.123766  0.358499  1.058544  1.260230   
          400  -0.951086 -0.104767 -0.724361 -0.580537  1.264942  1.349995   
          450  -0.949745 -0.736211  0.345561  0.249874  1.176831  1.464139   
          500  -0.939584  0.239072 -0.640911  0.020184  1.181445  1.598638   
          550  -0.375141 -0.995543 -2.468511  0.416273 -0.465723  0.905768   
          600  -0.030548 -1.192432 -1.801480  3.186237 -0.351648  0.591435   
          650  -0.013574 -2.087052 -0.720565  2.331540 -0.799730 -0.242654   
          700   0.294615 -0.885982 -0.627976 -0.271496 -0.721109 -0.798989   
          750   0.192319  0.114952  0.091069  0.021489 -1.010996 -0.859009   
          800   0.891598  0.890671  0.451285 -0.317333 -1.034908 -0.973947   
          850   1.367119  0.107399  0.161373 -0.300106 -0.588070 -0.929852   
          900   1.405764  0.103234  0.883697 -1.006657 -1.355346 -1.013540   
          950   1.575214 -0.062799  1.027753 -0.399047 -1.261162 -0.971334   

                      G7        G8        G9       G10  
condition time                                          
A         0    -0.899677  0.804977 -0.889359  0.708361  
          50   -0.906224  1.587897 -0.945905 -0.615681  
          100  -1.020254  0.407431 -1.034494 -0.903312  
          150  -0.989509  0.158872 -1.386365 -1.036012  
          200  -0.474129 -0.405608 -0.975077 -1.073984  
          250  -0.493646 -0.946827 -0.688258 -1.156093  
          300   0.882302 -1.265907 -0.026587 -1.049991  
          350   1.163199 -0.864747  0.851815 -0.989983  
          400   1.186729 -1.164204  1.763040 -1.059754  
          450   1.681313 -1.136106  1.341167 -1.121333  
          500   0.649119 -1.345739  1.415281 -0.993496  
          550   2.208214 -0.983780  0.941079  0.726206  
          600   0.786504 -0.533814  0.776734  0.622430  
          650   0.391701 -0.734053  0.730794  1.082830  
          700  -0.191543  0.420854  1.319809  1.147397  
          750  -0.539719  0.707833  0.135237  1.157381  
          800  -0.449491  0.807185 -0.307959  0.821923  
          850  -1.021770  0.679407 -0.823089  0.834685  
          900  -0.032347  0.935787 -0.675054  0.726725  
          950  -0.912598  1.125172 -0.974258  0.706422

In [25]:
gibbs.rvl[0].em.Y

G1        G2        G3        G4        G5        G6  \
condition time                                                               
A         50   -0.181595  1.801261  1.297516 -0.642793  0.828327 -1.091449   
          100  -0.684896  1.333486  0.580768 -0.580669  0.540489 -0.586762   
          150  -0.931874 -0.665083  0.809447 -0.567492  1.209848 -0.077659   
          200  -0.942176  0.015306  0.143316 -0.538813  0.936783  0.501003   
          250  -0.947633  0.586631 -0.215506  0.197373  0.802652  0.809808   
          300  -0.955327  0.158302 -0.483748 -0.359098  0.821430  1.044403   
          350  -0.958018  0.279842 -0.123766  0.358499  1.058544  1.260230   
          400  -0.951086 -0.104767 -0.724361 -0.580537  1.264942  1.349995   
          450  -0.949745 -0.736211  0.345561  0.249874  1.176831  1.464139   
          500  -0.939584  0.239072 -0.640911  0.020184  1.181445  1.598638   
          550  -0.375141 -0.995543 -2.468511  0.416273 -0.465723  0.905768   
          600  -0.030548 -1.192432 -1.801480  3.186237 -0.351648  0.591435   
          650  -0.013574 -2.087052 -0.720565  2.331540 -0.799730 -0.242654   
          700   0.294615 -0.885982 -0.627976 -0.271496 -0.721109 -0.798989   
          750   0.192319  0.114952  0.091069  0.021489 -1.010996 -0.859009   
          800   0.891598  0.890671  0.451285 -0.317333 -1.034908 -0.973947   
          850   1.367119  0.107399  0.161373 -0.300106 -0.588070 -0.929852   
          900   1.405764  0.103234  0.883697 -1.006657 -1.355346 -1.013540   
          950   1.575214 -0.062799  1.027753 -0.399047 -1.261162 -0.971334   
          1000  1.677220  2.047518  0.114507 -0.630055 -1.091058 -1.010994   

                      G7        G8        G9       G10  
condition time                                          
A         50   -0.906224  1.587897 -0.945905 -0.615681  
          100  -1.020254  0.407431 -1.034494 -0.903312  
          150  -0.989509  0.158872 -1.386365 -1.036012  
          200  -0.474129 -0.405608 -0.975077 -1.073984  
          250  -0.493646 -0.946827 -0.688258 -1.156093  
          300   0.882302 -1.265907 -0.026587 -1.049991  
          350   1.163199 -0.864747  0.851815 -0.989983  
          400   1.186729 -1.164204  1.763040 -1.059754  
          450   1.681313 -1.136106  1.341167 -1.121333  
          500   0.649119 -1.345739  1.415281 -0.993496  
          550   2.208214 -0.983780  0.941079  0.726206  
          600   0.786504 -0.533814  0.776734  0.622430  
          650   0.391701 -0.734053  0.730794  1.082830  
          700  -0.191543  0.420854  1.319809  1.147397  
          750  -0.539719  0.707833  0.135237  1.157381  
          800  -0.449491  0.807185 -0.307959  0.821923  
          850  -1.021770  0.679407 -0.823089  0.834685  
          900  -0.032347  0.935787 -0.675054  0.726725  
          950  -0.912598  1.125172 -0.974258  0.706422  
          1000 -1.018173  1.745371 -0.548550  1.465279

In [27]:
gibbs.rvHyperNetwork.currentValue = (['G4'], 'G1')

In [28]:
gibbs.rvl[0].currentValue = (['G4'], 'G1')
gibbs.rvl[1].currentValue = (['G3'], 'G1')
gibbs.rvl[2].currentValue = ([], 'G1')
gibbs.rvl[3].currentValue = (['G9'], 'G1')
gibbs.rvl[4].currentValue = ([], 'G1')

In [36]:
gibbs.rvl[0].em.logliks()

array([-24.02668697, -25.00390069, -24.93226968, -25.12049447,
       -24.3660514 , -25.21374421, -25.6812597 , -25.2796045 ,
       -25.48974582, -24.17365607, -25.89703105, -25.82556238,
       -25.17307171, -25.74005879, -26.36412817, -25.74847719,
       -26.27170732, -24.99029191, -25.75945955, -25.03889861,
       -25.59828053, -26.14924485, -25.66929167, -26.18396125,
       -24.82838645, -25.40598952, -25.9831917 , -26.42582027,
       -25.99720504, -26.43004007, -25.19582617, -25.40382892,
       -25.93297676, -25.45006018, -25.70202691, -24.56601956,
       -26.23904108, -25.82783532, -26.16481332, -25.18810441,
       -26.42602022, -26.42522717, -25.73947743, -26.32086292,
       -25.22031979, -25.50911447])

In [31]:
gibbs.rvl[0].getConditionalDistribution(gibbs.rvHyperNetwork.currentValue)

ValueError: need more than 1 value to unpack

In [33]:
gibbs.rvl[0].em.hypers

array([[ 1.,  1.,  1.]])

In [34]:
np.asarray([1,1,1])

array([1, 1, 1])

In [40]:
gibbs.rvl[4].em.logliks()

array([-27.94842096, -28.46665164, -29.0781069 , -28.82390752,
       -28.53816281, -28.43019909, -28.84927809, -28.55982025,
       -27.77355848, -28.57466288, -29.70720233, -29.33986634,
       -29.25606508, -28.97365973, -29.20768138, -29.04600484,
       -28.37672645, -28.98552891, -29.50705632, -28.963446  ,
       -29.33882978, -29.69164427, -29.34558523, -28.66785053,
       -29.46428668, -28.64870046, -29.23726034, -29.22040847,
       -29.50641332, -28.62718396, -29.02171106, -29.31539785,
       -29.29686552, -29.39833337, -28.79200426, -29.23326901,
       -28.94337461, -28.36961479, -28.26969314, -28.75291411,
       -29.0152651 , -28.76489936, -29.44044933, -28.27131879,
       -29.11172897, -28.58514066])

In [44]:
3*np.log(sp.stats.gamma.pdf(1,a=10,scale=0.1))

0.67207034957697143

In [48]:
gibbs.rvHyperNetwork.getConditionalDistribution([(['G4'], 'G1'),(['G3'], 'G1'),([], 'G1'),(['G9'], 'G1'),([], 'G1')],[1,1,1,1,1])

array([  8.30603093e-01,   5.59655962e-03,   4.13532930e-02,
         4.13532930e-02,   5.59655962e-03,   5.59655962e-03,
         5.59655962e-03,   5.59655962e-03,   4.13532930e-02,
         5.59655962e-03,   2.78636296e-04,   2.78636296e-04,
         3.77093221e-05,   3.77093221e-05,   3.77093221e-05,
         3.77093221e-05,   2.78636296e-04,   3.77093221e-05,
         2.05885922e-03,   2.78636296e-04,   2.78636296e-04,
         2.78636296e-04,   2.78636296e-04,   2.05885922e-03,
         2.78636296e-04,   2.78636296e-04,   2.78636296e-04,
         2.78636296e-04,   2.78636296e-04,   2.05885922e-03,
         2.78636296e-04,   3.77093221e-05,   3.77093221e-05,
         3.77093221e-05,   2.78636296e-04,   3.77093221e-05,
         3.77093221e-05,   3.77093221e-05,   2.78636296e-04,
         3.77093221e-05,   3.77093221e-05,   2.78636296e-04,
         3.77093221e-05,   2.78636296e-04,   3.77093221e-05,
         2.78636296e-04])

In [49]:
gibbs.rvl[0].getConditionalDistribution((['G4'], 'G1'))

array([ 0.18778552,  0.02599975,  0.02793046,  0.17097084,  0.04920209,
        0.02107828,  0.01320675,  0.01973479,  0.01599445,  0.05964029,
        0.00391555,  0.03107567,  0.00807615,  0.00458105,  0.00245434,
        0.00454265,  0.00269199,  0.00969583,  0.03319927,  0.00923581,
        0.00527884,  0.00304269,  0.00491699,  0.00293887,  0.01139986,
        0.04727577,  0.02654379,  0.01705029,  0.02617442,  0.01697849,
        0.05833261,  0.00641192,  0.0037773 ,  0.00612224,  0.00475863,
        0.01481986,  0.00278138,  0.00419609,  0.00299569,  0.00795566,
        0.00230704,  0.00230887,  0.00458372,  0.00256286,  0.00770345,
        0.00577116])

In [50]:
gibbs.rvl[0].em.logliks()

array([-24.02668697, -25.00390069, -24.93226968, -25.12049447,
       -24.3660514 , -25.21374421, -25.6812597 , -25.2796045 ,
       -25.48974582, -24.17365607, -25.89703105, -25.82556238,
       -25.17307171, -25.74005879, -26.36412817, -25.74847719,
       -26.27170732, -24.99029191, -25.75945955, -25.03889861,
       -25.59828053, -26.14924485, -25.66929167, -26.18396125,
       -24.82838645, -25.40598952, -25.9831917 , -26.42582027,
       -25.99720504, -26.43004007, -25.19582617, -25.40382892,
       -25.93297676, -25.45006018, -25.70202691, -24.56601956,
       -26.23904108, -25.82783532, -26.16481332, -25.18810441,
       -26.42602022, -26.42522717, -25.73947743, -26.32086292,
       -25.22031979, -25.50911447])

In [65]:
gibbs.rvl[0].em.hypers = np.array([1,1,1])

In [66]:
old_hypers = gibbs.rvl[0].em.hypers

In [88]:
new_hypers = np.array([1,1,np.exp(0.2)])

In [89]:
gibbs.rvl[0].thetajump.pset = [gibbs.rvl[0].currentValue]

In [90]:
gibbs.rvl[0].currentValue

(['G4'], 'G1')

In [91]:
gibbs.rvl[0].thetajump.pset

[(['G4'], 'G1')]

In [92]:
            gibbs.rvl[0].thetajump.hypers = new_hypers
            new_ll = gibbs.rvl[0].thetajump.logliks()

In [93]:
new_ll

array([-28.59491372])

In [94]:
            gibbs.rvl[0].thetajump.hypers = old_hypers
            old_ll = gibbs.rvl[0].thetajump.logliks()

In [95]:
old_ll

array([-26.18396125])

In [96]:
            (new_ll,old_ll) = (new_ll,old_ll)-np.max((new_ll,old_ll))
            i=0

In [97]:
            p_hypers_old = np.prod(sp.stats.gamma.pdf(old_hypers,a=gibbs.rvl[i].em._prior_shape,scale=gibbs.rvl[i].em._prior_scale))
            p_hypers_new = np.prod(sp.stats.gamma.pdf(new_hypers,a=gibbs.rvl[i].em._prior_shape,scale=gibbs.rvl[i].em._prior_scale))

In [98]:
p_accept_theta = (sp.exp(new_ll) * p_hypers_new) / (sp.exp(old_ll) * p_hypers_old)

In [99]:
p_accept_theta

array([ 0.05930984])

In [100]:
gibbs.rvl[0].thetajump.logliks()

array([-26.18396125])

In [101]:
old_hypers

array([1, 1, 1])

In [102]:
gibbs.rvl[0].thetajump.hypers

array([1, 1, 1])

In [104]:
gibbs.rvl[0].thetajump.pset

[(['G4'], 'G1')]

In [105]:
gibbs.rvl[0].thetajump.logliks()

array([-26.18396125])

In [106]:
gibbs.rvl[0].em.hypers

array([1, 1, 1])

In [107]:
gibbs.rvl[0].em.logliks()

array([-24.02668697, -25.00390069, -24.93226968, -25.12049447,
       -24.3660514 , -25.21374421, -25.6812597 , -25.2796045 ,
       -25.48974582, -24.17365607, -25.89703105, -25.82556238,
       -25.17307171, -25.74005879, -26.36412817, -25.74847719,
       -26.27170732, -24.99029191, -25.75945955, -25.03889861,
       -25.59828053, -26.14924485, -25.66929167, -26.18396125,
       -24.82838645, -25.40598952, -25.9831917 , -26.42582027,
       -25.99720504, -26.43004007, -25.19582617, -25.40382892,
       -25.93297676, -25.45006018, -25.70202691, -24.56601956,
       -26.23904108, -25.82783532, -26.16481332, -25.18810441,
       -26.42602022, -26.42522717, -25.73947743, -26.32086292,
       -25.22031979, -25.50911447])

In [108]:
gibbs.rvl[0].thetajump = gibbs.rvl[0].em

In [109]:
gibbs.rvl[0].thetajump.pset = [(['G4'],'G1')]

In [110]:
gibbs.rvl[0].em.pset

[(['G4'], 'G1')]

In [112]:
gibbs.rvl[1].thetajump.X

G1        G2        G3        G4        G5        G6  \
condition time                                                               
B         0     2.811939  1.398249  1.271453 -1.096371 -1.089325 -1.348185   
          50    2.001214  1.295680  0.518649 -0.846412 -1.037908 -1.208067   
          100   1.496530  1.701773 -0.246678 -1.056045 -0.853977 -1.321993   
          150   1.222923  1.189476 -0.789163 -0.339307 -0.989400 -1.341569   
          200   0.027907  0.307980 -0.913661  0.188339 -0.526999 -1.269581   
          250  -0.597866  0.066799 -0.910224  1.006056  0.425897 -0.230874   
          300  -0.471536 -0.934721 -1.167661  1.106919  1.093150  0.259141   
          350  -0.619244 -1.113515 -1.108420  1.015956  0.995108  0.757507   
          400  -0.371773 -1.120883 -1.105669  0.772747  1.436659  0.728570   
          450  -0.603853 -1.346369 -0.857637  1.025194  1.225013  0.902961   
          500  -0.517122 -1.134226 -0.944695  1.357010  0.962941  0.879983   
          550  -0.593600 -1.026508 -1.218789  1.366836  1.530552  1.439262   
          600  -0.649470 -0.789009 -0.215677  1.581907  0.928743  0.848401   
          650   0.053387 -0.217851  0.538201  0.155054  1.044924  1.079771   
          700  -0.303350  0.121673  0.697297 -0.720160  0.022271  0.961279   
          750  -0.747691 -1.006079  0.758856 -0.884613 -0.644902  0.897048   
          800  -0.652860  0.412187  0.848135 -0.855804 -0.762596  0.526529   
          850  -0.275664  0.218933  1.320009 -1.114115 -0.731757  0.181803   
          900  -0.090620  0.766933  0.814883 -0.769662 -0.996329 -0.530319   
          950  -0.723676 -0.169403  1.921649 -0.977311 -0.971602 -0.992499   

                      G7        G8        G9       G10  
condition time                                          
B         0    -1.228006  2.854934 -2.417929  1.038124  
          50   -1.262608 -0.189518 -2.241517 -0.679168  
          100  -0.941811 -0.496355 -0.665507 -0.987745  
          150   0.090403 -0.794618 -0.237734 -0.944457  
          200   0.580794 -0.745983  0.941738 -0.968810  
          250   1.521747 -0.815256  0.895317 -1.067341  
          300   1.130378 -0.821709  0.791440 -0.940353  
          350   1.333642 -0.833223  1.122859 -1.006089  
          400   1.125906 -0.910341  0.251251 -1.025548  
          450   1.410334 -0.877114 -0.027125 -1.236056  
          500   1.177864 -0.893578  0.891022 -1.125179  
          550   0.785530 -0.277576  0.380479  0.295639  
          600   0.191936 -0.056350 -0.171478  0.840855  
          650  -0.165798  0.090758  0.081817  0.638060  
          700  -0.665437  0.157829  1.039444  1.150917  
          750  -0.896146  0.233732  1.005391  0.806829  
          800  -0.801104  0.217638  0.534564  0.870153  
          850  -0.557040  0.489844 -0.564963  1.112473  
          900  -0.704525  0.579291 -0.018383  0.784477  
          950  -0.981075  1.101641 -0.631289  1.249213

In [113]:
class RandomVariableCondition(ag.RandomVariable):
    def __init__(self, csidata, cond, gene, gpprior, betaprior, depth, standardise):
    #override init to include all sorts of CSI stuffs
        #extract the data frame columns that actually have our condition's data
        #(without killing the fine balance of the tuple indexing)
        colNames = np.asarray([x[0] for x in csidata.columns.values])
        numtemp = np.arange(len(colNames))
        inp = csidata.iloc[:,numtemp[colNames==cond]]
        #standardising
        if standardise:
            inp[:][:] = sp.stats.mstats.zscore(inp,axis=1,ddof=1)
        #some processing stuff borrowed from the CSI code
        assert (inp.columns.is_monotonic_increasing)
        self.cc = csi.Csi(inp)
        self.em = self.cc.getEm()
        if gpprior:
            self.em.set_priors(gpprior[0], gpprior[1])
        #prepare the EM object
        self.em.setup(self.cc.allParents(gene,depth))
        #beta initialised at 1 as per Chris recommendation
        self.beta = 1
        self.betaprior = betaprior
        #MCMC constants
        self.thetaconst = 1
        self.betaconst = 1
        self.thetacount = 0
        self.betacount = 0
        #random initialisation
        ind = np.random.choice(np.arange(len(self.em.pset)),size=1)
        self.currentValue = self.em.pset[ind]
        self.valRange = self.em.pset
        self.distribution = list(range(len(self.valRange)))
        #create helper EM object for theta tuning
        #initialise its hyperparameters to be the same as the main EM object
        cctemp = csi.Csi(inp)
        self.thetajump = cctemp.getEm()
        self.thetajump.setup([self.currentValue])
        self.thetajump.hypers = self.em.hypers
    
    def getConditionalDistribution(self, hyperparent):
    #override with actual computation
        i = 0
        logliks = self.em.logliks()
        #turn logliks into actual numbers, scaled to the largest one
        logliks = np.exp(logliks-np.max(logliks))
        #for each possible value of the RV
        for v in self.getValRange():
            #skipping P(theta) and all the Z's as they're the same for each parent combo
            p =  logliks[i] * np.exp((-1)*self.beta*hamming(v,hyperparent))
            #set the distribution
            self.distribution[i] = p
            i = i + 1
        self.normalizeDistribution()
        return self.distribution
    
    def normalizeDistribution(self):
    #we actually need the normalisation
        self.distribution = self.distribution/np.sum(self.distribution)

In [129]:
rvl = RandomVariableCondition(inp,'A','G1',gpprior,betaprior,2,True)

//anaconda/lib/python3.4/site-packages/ipykernel/__main__.py:30: DeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future


In [130]:
rvl.em.hypers = np.array([1,1,1])

In [131]:
rvl.thetajump.hypers = np.array([1,1,1])

In [132]:
rvl.thetajump.pset = [(['G4'],'G1')]

In [133]:
rvl.thetajump.logliks()

array([-24.02668697])

In [134]:
rvl.em.logliks()

array([-24.02668697, -25.00390069, -24.93226968, -25.12049447,
       -24.3660514 , -25.21374421, -25.6812597 , -25.2796045 ,
       -25.48974582, -24.17365607, -25.89703105, -25.82556238,
       -25.17307171, -25.74005879, -26.36412817, -25.74847719,
       -26.27170732, -24.99029191, -25.75945955, -25.03889861,
       -25.59828053, -26.14924485, -25.66929167, -26.18396125,
       -24.82838645, -25.40598952, -25.9831917 , -26.42582027,
       -25.99720504, -26.43004007, -25.19582617, -25.40382892,
       -25.93297676, -25.45006018, -25.70202691, -24.56601956,
       -26.23904108, -25.82783532, -26.16481332, -25.18810441,
       -26.42602022, -26.42522717, -25.73947743, -26.32086292,
       -25.22031979, -25.50911447])

In [128]:
class RandomVariableCondition(ag.RandomVariable):
    def __init__(self, csidata, cond, gene, gpprior, betaprior, depth, standardise):
    #override init to include all sorts of CSI stuffs
        #extract the data frame columns that actually have our condition's data
        #(without killing the fine balance of the tuple indexing)
        colNames = np.asarray([x[0] for x in csidata.columns.values])
        numtemp = np.arange(len(colNames))
        inp = csidata.iloc[:,numtemp[colNames==cond]]
        #standardising
        if standardise:
            inp[:][:] = sp.stats.mstats.zscore(inp,axis=1,ddof=1)
        #some processing stuff borrowed from the CSI code
        assert (inp.columns.is_monotonic_increasing)
        self.cc = csi.Csi(inp)
        self.em = self.cc.getEm()
        if gpprior:
            self.em.set_priors(gpprior[0], gpprior[1])
        #prepare the EM object
        self.em.setup(self.cc.allParents(gene,depth))
        #beta initialised at 1 as per Chris recommendation
        self.beta = 1
        self.betaprior = betaprior
        #MCMC constants
        self.thetaconst = 1
        self.betaconst = 1
        self.thetacount = 0
        self.betacount = 0
        #random initialisation
        ind = np.random.choice(np.arange(len(self.em.pset)),size=1)
        self.currentValue = self.em.pset[ind]
        self.valRange = self.em.pset
        self.distribution = list(range(len(self.valRange)))
        #create helper EM object for theta tuning
        #initialise its hyperparameters to be the same as the main EM object
        self.thetajump = self.cc.getEm()
        self.thetajump.setup(self.cc.allParents(gene,depth))
        self.thetajump.hypers = self.em.hypers
    
    def getConditionalDistribution(self, hyperparent):
    #override with actual computation
        i = 0
        logliks = self.em.logliks()
        #turn logliks into actual numbers, scaled to the largest one
        logliks = np.exp(logliks-np.max(logliks))
        #for each possible value of the RV
        for v in self.getValRange():
            #skipping P(theta) and all the Z's as they're the same for each parent combo
            p =  logliks[i] * np.exp((-1)*self.beta*hamming(v,hyperparent))
            #set the distribution
            self.distribution[i] = p
            i = i + 1
        self.normalizeDistribution()
        return self.distribution
    
    def normalizeDistribution(self):
    #we actually need the normalisation
        self.distribution = self.distribution/np.sum(self.distribution)

In [138]:
def loglik(X,Y,hypers):
	#hypers as [length, signal std, noise std] in log space
	thing = X / sp.exp(hypers[0])
	dist = np.zeros((len(Y),len(Y)))
	for i in np.arange(len(Y)):
		for j in np.arange(len(Y)):
			dist[i,j] = np.sum(np.square(thing[i,:]-thing[j,:]))
	K = sp.exp(2*hypers[1]+(-1/2)*dist)
	L = spl.cho_factor(K + sp.exp(2*hypers[2])*npm.eye(len(Y)))
	alpha = spl.cho_solve(L,Y)
	out = (-0.5)*np.dot(np.transpose(Y),alpha)-np.sum(np.log(np.diag(L[0])))-(X.shape[0]/2)*np.log(2*math.pi)
	return out

In [141]:
new_ll = loglik(rvl.em.X.iloc[:,[0,3]].values, rvl.em.Y.iloc[:,0].values, [0,0,0.2])

In [137]:
import numpy.matlib as npm
import scipy.linalg as spl
import math

In [144]:
            p_hypers_old = np.prod(sp.stats.gamma.pdf(old_hypers,a=gibbs.rvl[i].em._prior_shape,scale=gibbs.rvl[i].em._prior_scale))
            p_hypers_new = np.prod(sp.stats.gamma.pdf(new_hypers,a=gibbs.rvl[i].em._prior_shape,scale=gibbs.rvl[i].em._prior_scale))

In [145]:
p_accept_theta = (sp.exp(new_ll) * p_hypers_new) / (sp.exp(old_ll) * p_hypers_old)

In [146]:
p_accept_theta

0.051293290663270014

In [147]:
gibbs.rvHyperNetwork.currentValue

(['G4'], 'G1')

In [148]:
gibbs.rvl[0].currentValue

(['G4'], 'G1')

In [149]:
old_beta = 1
new_beta = 1.2

In [151]:
            p_beta_old = sp.exp((-1)*old_beta*0) * sp.stats.gamma.pdf(old_beta,a=gibbs.rvl[i].betaprior[0],scale=gibbs.rvl[i].betaprior[1])
            p_beta_new = sp.exp((-1)*new_beta*0) * sp.stats.gamma.pdf(new_beta,a=gibbs.rvl[i].betaprior[0],scale=gibbs.rvl[i].betaprior[1])
            p_accept_beta = p_beta_new/p_beta_old

In [152]:
p_accept_beta

0.81873075307798193

In [157]:
np.log(sp.stats.gamma.pdf(1,a=1,scale=1)*np.power(sp.stats.gamma.pdf(1,a=1,scale=1),4))

-5.0

In [158]:
p_beta_old

0.36787944117144233

In [159]:
p_beta_new

0.30119421191220214

In [160]:
gibbs.rvl[0].betaprior

[1, 1]

In [164]:
vals = gibbs.rvl[1].em.pset

In [167]:
Z = np.zeros(len(vals))

In [168]:
for i in np.arange(len(vals)):
    Z[i] = hamming(vals[i],(['G4'],'G1'))

In [169]:
Z

array([ 1.,  2.,  2.,  0.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,  1.,  3.,
        3.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,  3.,  3.,  3.,  1.,
        1.,  1.,  1.,  1.,  1.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [170]:
const_old = np.sum(np.exp((-1)*Z))

In [171]:
const_new = np.sum(np.exp((-1.2)*Z))

In [172]:
const_old

6.7876351507360706

In [173]:
const_new

5.2015557620493098

In [174]:
            p_beta_old = sp.exp((-1)*old_beta*0)/const_old * sp.stats.gamma.pdf(old_beta,a=1,scale=1)
            p_beta_new = sp.exp((-1)*new_beta*0)/const_new * sp.stats.gamma.pdf(new_beta,a=1,scale=1)
            p_accept_beta = p_beta_new/p_beta_old

In [175]:
p_accept_beta

1.0683814406310008

In [176]:
i=1

In [177]:
            Z = np.zeros(len(gibbs.rvl[i].em.pset))
            for j in np.arange(len(gibbs.rvl[i].em.pset)):
                Z[i] = hamming(gibbs.rvl[i].em.pset[j],gibbs.rvHyperNetwork.currentValue)
            const_old = np.sum(np.exp((-1)*old_beta*Z))
            const_new = np.sum(np.exp((-1)*new_beta*Z))

In [178]:
const_old

45.049787068367863

In [179]:
const_new

45.027323722447292

In [180]:
Z

array([ 0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [182]:
            Z = np.zeros(len(gibbs.rvl[i].em.pset))
            for j in np.arange(len(gibbs.rvl[i].em.pset)):
                Z[j] = hamming(gibbs.rvl[i].em.pset[j],gibbs.rvHyperNetwork.currentValue)
            const_old = np.sum(np.exp((-1)*old_beta*Z))
            const_new = np.sum(np.exp((-1)*new_beta*Z))

In [183]:
Z

array([ 1.,  2.,  2.,  0.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,  1.,  3.,
        3.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,  3.,  3.,  3.,  1.,
        1.,  1.,  1.,  1.,  1.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [184]:
const_old

6.7876351507360706

In [185]:
const_new

5.2015557620493098

In [189]:
list(gibbs.rvl[1].em.X.columns)

['G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10']

In [190]:
def loglik_local(em, our_pset, hypers):
	'''Compute a single instance of a log likelihood with altered hyperparameters'''
	X = em.X.values
	Y = em.Y.values
	genes = list(em.X.columns)
	inds_X = []
	inds_Y = []
	for i in np.arange(len(genes)):
		if genes[i] in our_pset[0]:
			inds_X.append(i)
		if genes[i] == our_pset[1]:
			inds_Y.append(i)
	return (inds_X, inds_Y)

In [193]:
loglik_local(gibbs.rvl[1].em, (['G4','G8'],'G1'), 'cat')

([3, 7], [0])

In [194]:
X = gibbs.rvl[1].em.X.values

In [195]:
X[:,[3]]

array([[-1.09637118],
       [-0.84641153],
       [-1.05604545],
       [-0.33930679],
       [ 0.18833872],
       [ 1.00605597],
       [ 1.10691875],
       [ 1.0159559 ],
       [ 0.77274696],
       [ 1.02519388],
       [ 1.35700956],
       [ 1.3668358 ],
       [ 1.58190749],
       [ 0.15505367],
       [-0.72016021],
       [-0.88461276],
       [-0.85580391],
       [-1.11411499],
       [-0.76966206],
       [-0.97731056]])

In [226]:
def loglik_local(em, our_pset, hypers):
	'''Compute a single instance of a log likelihood with altered hyperparameters'''
	#extract data
	X = em.X.values
	Y = em.Y.values
	#what's actually in our parental set?
	genes = list(em.X.columns)
	inds_X = []
	inds_Y = []
	for i in np.arange(len(genes)):
		if genes[i] in our_pset[0]:
			inds_X.append(i)
		if genes[i] == our_pset[1]:
			inds_Y.append(i)
			inds_X.append(i)
	#now we can take the appropriate data chunks
	X = X[:,inds_X]
	Y = Y[:,inds_Y]
	#likelihood computation proper
	thing = X / hypers[1]
	dist = np.zeros((len(Y),len(Y)))
	for i in np.arange(len(Y)):
		for j in np.arange(len(Y)):
			dist[i,j] = np.sum(np.square(thing[i,:]-thing[j,:]))
	K = hypers[0]*hypers[0]*sp.exp((-1/2)*dist)
	L = spl.cho_factor(K + hypers[2]*hypers[2]*npm.eye(len(Y)))
	alpha = spl.cho_solve(L,Y)
	out = (-0.5)*np.dot(np.transpose(Y),alpha)-np.sum(np.log(np.diag(L[0])))-(X.shape[0]/2)*np.log(2*math.pi)
	return out[0][0]

In [220]:
loglik_local(gibbs.rvl[0].em,(['G4'],'G1'),old_hypers)

array([[-25.12049441]])

In [198]:
gibbs.rvl[0].em.pset

[(['G4'], 'G1')]

In [199]:
gibbs.rvl[0].em.hypers

array([1, 1, 1])

In [200]:
gibbs.rvl[0].em.logliks()

array([-24.02668697, -25.00390069, -24.93226968, -25.12049447,
       -24.3660514 , -25.21374421, -25.6812597 , -25.2796045 ,
       -25.48974582, -24.17365607, -25.89703105, -25.82556238,
       -25.17307171, -25.74005879, -26.36412817, -25.74847719,
       -26.27170732, -24.99029191, -25.75945955, -25.03889861,
       -25.59828053, -26.14924485, -25.66929167, -26.18396125,
       -24.82838645, -25.40598952, -25.9831917 , -26.42582027,
       -25.99720504, -26.43004007, -25.19582617, -25.40382892,
       -25.93297676, -25.45006018, -25.70202691, -24.56601956,
       -26.23904108, -25.82783532, -26.16481332, -25.18810441,
       -26.42602022, -26.42522717, -25.73947743, -26.32086292,
       -25.22031979, -25.50911447])

In [204]:
old_hypers

array([1, 1, 1])

In [205]:
new_hypers

array([ 1.        ,  1.        ,  1.22140276])

In [221]:
            old_ll = loglik_local(gibbs.rvl[0].em, (['G4'],'G1'), old_hypers)
            new_ll = loglik_local(gibbs.rvl[0].em, (['G4'],'G1'), new_hypers)
            #numeric thing before exping, scale to largest likelihood
            (new_ll,old_ll) = (new_ll,old_ll)-np.max((new_ll,old_ll))
            #compute P(hypers)
            p_hypers_old = np.prod(sp.stats.gamma.pdf(old_hypers,a=gibbs.rvl[i].em._prior_shape,scale=gibbs.rvl[i].em._prior_scale))
            p_hypers_new = np.prod(sp.stats.gamma.pdf(new_hypers,a=gibbs.rvl[i].em._prior_shape,scale=gibbs.rvl[i].em._prior_scale))
            #transition probability
            p_accept_theta = (sp.exp(new_ll) * p_hypers_new) / (sp.exp(old_ll) * p_hypers_old)

In [222]:
p_accept_theta

array([[ 0.05129329]])

In [223]:
old_ll

array([[ 0.]])

In [210]:
i

1

In [211]:
i=0

In [213]:
p_accept_theta

0.051293290663270014

In [214]:
old_ll

0.0

In [215]:
new_ll

-2.5561677400480178

In [224]:
loglik_local(gibbs.rvl[0].em, (['G4'],'G1'), old_hypers)

array([[-25.12049441]])

In [225]:
loglik_local(gibbs.rvl[0].em, (['G4'],'G1'), new_hypers)

array([[-27.67666215]])

In [228]:
np.log(p_hypers_new)

0.25804276797527054

In [229]:
np.log(p_hypers_old)

0.67207034957697154