In [1]:
import numpy as np
import pandas as pd

In [2]:
    R = pd.read_csv('dummy.csv', index_col=0, header=[0,1])
    R.index = map(lambda x:x.upper(), R.index.tolist())
    old_colnames = R.columns.values.tolist()
    new_colnames = []
    for lab in old_colnames:
        new_colnames.append((lab[0].title(), float(lab[1])))
    R.columns = pd.MultiIndex.from_tuples(new_colnames,names=['Treatment','Time'])

//anaconda/lib/python3.4/site-packages/IPython/core/interactiveshell.py:3066: PerformanceWarning: indexing past lexsort depth may impact performance.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [4]:
R

Treatment  A                 B               
Time       0  2  4  0  2  4  0  2  4  0  2  4
G1         1  1  1  1  1  1  1  1  1  1  1  1
G2         1  1  1  1  1  1  1  1  1  1  1  1
G3         1  1  1  1  1  1  1  1  1  1  1  1

In [5]:
    condnames = np.array([x[0] for x in new_colnames])
    tps = np.array([x[1] for x in new_colnames])
    conds = np.unique(condnames)

In [6]:
len(conds)

2

In [7]:
np.sum(condnames==conds[0])!=np.sum(condnames==conds[1])

False

In [8]:
    tp_conds = []
    for cond in conds:
        cond_tps = tps[condnames==cond]
        #we should have the same exact number of reps per time point
        #so if we count up how many reps we have per time point, there should only be one unique value
        tpholder, inverse = np.unique(cond_tps, return_inverse=True)
        if len(np.unique(np.bincount(inverse)))!=1:
            #sys.stderr.write('ERROR: Non-uniformity of time points for replicates detected in condition '+cond+'. Exiting\n')
            #sys.exit(1)
        #well, if not, then we're fine and can store information
        tp_conds.append(tpholder)
        Nrepl = np.bincount(inverse)[0]

IndentationError: expected an indented block (<ipython-input-8-a76a551d04a1>, line 11)

In [9]:
    tp_conds = []
    for cond in conds:
        cond_tps = tps[condnames==cond]
        #we should have the same exact number of reps per time point
        #so if we count up how many reps we have per time point, there should only be one unique value
        tpholder, inverse = np.unique(cond_tps, return_inverse=True)
        #if len(np.unique(np.bincount(inverse)))!=1:
            #sys.stderr.write('ERROR: Non-uniformity of time points for replicates detected in condition '+cond+'. Exiting\n')
            #sys.exit(1)
        #well, if not, then we're fine and can store information
        tp_conds.append(tpholder)
        Nrepl = np.bincount(inverse)[0]

In [10]:
tp_conds

[array([ 0.,  2.,  4.]), array([ 0.,  2.,  4.])]

In [11]:
Nrepl

2

In [12]:
len(np.unique(np.bincount(inverse)))

1

In [13]:
tp_conds[0]!=tp_conds[1]

array([False, False, False], dtype=bool)

In [14]:
np.array_equal(tp_conds[0],tp_conds[1])

True

In [15]:
Tc = tp_conds[0]

In [16]:
Tc

array([ 0.,  2.,  4.])

In [17]:
Ngenes = R.shape[0]

In [18]:
import scipy as SP

In [19]:
T  = SP.zeros([Nrepl,Tc.shape[0]])

In [20]:
T

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
T[:,:] = Tc

In [22]:
T

array([[ 0.,  2.,  4.],
       [ 0.,  2.,  4.]])

In [23]:
Tpredict = SP.linspace(T.min(),T.max(),20)[:,newaxis]

NameError: name 'newaxis' is not defined

In [24]:
Ngenes

3

In [25]:
len(Tc)

3

In [26]:
R.index

Index(['G1', 'G2', 'G3'], dtype='object')

In [32]:
Y0 = R.loc['G1'][conds[0]]

In [33]:
Y0

Time
0    1
2    1
4    3
0    1
2    1
4    1
Name: G1, dtype: int64

In [30]:
R.iloc[0,2]=3

In [31]:
R

Treatment  A                 B               
Time       0  2  4  0  2  4  0  2  4  0  2  4
G1         1  1  3  1  1  1  1  1  1  1  1  1
G2         1  1  1  1  1  1  1  1  1  1  1  1
G3         1  1  1  1  1  1  1  1  1  1  1  1

In [36]:
np.reshape(Y0,(2,3))

array([[1, 1, 3],
       [1, 1, 1]])

In [38]:
Y01=Y0.values

In [39]:
np.reshape(Y01,(2,3))

array([[1, 1, 3],
       [1, 1, 1]])

In [40]:
Y0_hold = R.loc['G1'][conds[0]].values

In [41]:
Y0_hold

array([1, 1, 3, 1, 1, 1])

In [42]:
Y0 = np.reshape(Y0_hold,(Nreps,len(Tc)),order='C')

NameError: name 'Nreps' is not defined

In [43]:
Y0 = np.reshape(Y0_hold,(Nrepl,len(Tc)),order='C')

In [44]:
Y0

array([[1, 1, 3],
       [1, 1, 1]])

In [45]:
str(Y0)

'[[1 1 3]\n [1 1 1]]'

In [46]:
T.shape

(2, 3)

In [47]:
T

array([[ 0.,  2.,  4.],
       [ 0.,  2.,  4.]])

In [48]:
R.columns[0][0]

'A'

In [49]:
R.columns[-1][0]

'B'

In [53]:
Tc11 = np.unique([x[1] for x in list(R.columns)])

In [54]:
Tc11

array([ 0.,  2.,  4.])

In [55]:
Nrepl11 = R.shape[1]/(2*len(Tc11))

In [56]:
Nrepl11

2.0

In [58]:
Tpredict = SP.linspace(T.min(),T.max(),20)

In [59]:
Tpredict

array([ 0.        ,  0.21052632,  0.42105263,  0.63157895,  0.84210526,
        1.05263158,  1.26315789,  1.47368421,  1.68421053,  1.89473684,
        2.10526316,  2.31578947,  2.52631579,  2.73684211,  2.94736842,
        3.15789474,  3.36842105,  3.57894737,  3.78947368,  4.        ])

In [61]:
Tpredict = SP.linspace(T.min(),T.max(),20)[:,None]

In [62]:
Tpredict

array([[ 0.        ],
       [ 0.21052632],
       [ 0.42105263],
       [ 0.63157895],
       [ 0.84210526],
       [ 1.05263158],
       [ 1.26315789],
       [ 1.47368421],
       [ 1.68421053],
       [ 1.89473684],
       [ 2.10526316],
       [ 2.31578947],
       [ 2.52631579],
       [ 2.73684211],
       [ 2.94736842],
       [ 3.15789474],
       [ 3.36842105],
       [ 3.57894737],
       [ 3.78947368],
       [ 4.        ]])

In [63]:
T

array([[ 0.,  2.,  4.],
       [ 0.,  2.,  4.]])